version: '3'
volumes:
  postgres:
services:
  db:
    image: postgres:9.6
    environment: 
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres
  app:
    image: node:14.3
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: bash ./app.sh
    depends_on:
      - db
    networks:
      - postgres
      - app
    ports:
      - 9229:9229
  client: 
    image: nginx:1.19
    volumes:
      - ./app/public:/usr/share/nginx/html
      - ./app/public/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app
    ports:
      - 80:80
networks:
  postgres:
  app:
